# Generated by Django 6.0.5 on 2026-05-10 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
